openapi:        '3.0.3'
info:
  description:  API for jellyapp project
  version:      0.1.0
  title:        Jellyapp Project
servers:
  - url: /api/v0

paths:


components:
  schemas:

  responses:

  requestBodies:
